version: "3.9"
services:
  api:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app

    command:
      ["bash", "-c", "python wait-for-postgresql.py && bash entrypoint.sh"]
    depends_on:
      - postgresql

  postgresql:
    image: postgis/postgis:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
