# Generated by Django 5.0.4 on 2024-04-21 13:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=256)),
                ('driver', models.CharField(max_length=256)),
                ('map_schema', django.contrib.gis.db.models.fields.LineStringField(srid=4326)),
            ],
        ),
    ]
